# Generated by Django 5.0.2 on 2024-03-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('Bookid', models.IntegerField(primary_key=True, serialize=False)),
                ('Bookname', models.CharField(max_length=40)),
                ('Author', models.CharField(max_length=20)),
                ('published', models.DateField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
